TodoWebApp/Controllers/TodoItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TodoWebApp.Models;

using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using System.Diagnostics;

namespace TodoWebApp.Controllers
{[Authorize]
    public class TodoItemsController : Controller
    {
        private readonly TodoDataContext _context;

        public TodoItemsController()
        {
            _context = new TodoDataContext();
        }

        // GET: TodoItems
        //public IActionResult Index(int del) {
        //    var List = _context.TodoItems.ToList();
        //    List = List.Where(m => m.Done).ToList();
        //    return View(List);
        //}
        public ActionResult DeleteCompleted() {
            var List = _context.TodoItems.ToList();
            List = List.Where(m => m.Done).ToList();
            foreach (var a in List)
            {
                _context.TodoItems.Remove(a);
            }
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Index(string filter)
        {
            var Username = User.Identity.GetUserName(); 
            var List = _context.TodoItems.Where(m => m.UserId == Username).ToList();

            if (!String.IsNullOrEmpty(filter))
            {
                if (filter.Equals("com"))
                {
                    List = List.Where(m => m.Done).ToList();


                    return View(List);
                }
                else if (filter.Equals("incom"))
                {
                    List = List.Where(m => !m.Done).ToList();

                    return View(List);

                }
            }
            return View(List);
        }
        // GET: TodoItems/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var todoItem = await _context.TodoItems
                .SingleOrDefaultAsync(m => m.Id == id);
            if (todoItem == null)
            {
                return HttpNotFound();
            }

            return View(todoItem);
        }

        // GET: odoItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TodoItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include ="Id,Value,Done")] TodoItem todoItem)
        {
            if (ModelState.IsValid)
            {
                todoItem.UserId = User.Identity.GetUserName();
                _context.TodoItems.Add(todoItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(todoItem);
        }

        // GET: TodoItems/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var todoItem = await _context.TodoItems.SingleOrDefaultAsync(m => m.Id == id);
            if (todoItem == null)
            {
                return HttpNotFound();
            }
            return View(todoItem);
        }

        // POST: TodoItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind(Include ="Id,Value,Done")] TodoItem todoItem)
        {
          

            if (id != todoItem.Id)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                    var dbitem = _context.TodoItems.Find(id);
                    dbitem.LastAccessed = DateTime.Now;
                    dbitem.Value = todoItem.Value;
                    dbitem.Done = todoItem.Done;
                    if (todoItem.Done) {
                        dbitem.CompleteDate = DateTime.Now;
                        
                    }
                    

                    // TODO _context.Update(todoItem);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    if (!TodoItemExists(todoItem.Id))
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(todoItem);
        }

        // GET: TodoItems/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var todoItem = await _context.TodoItems
                .SingleOrDefaultAsync(m => m.Id == id);
            if (todoItem == null)
            {
                return HttpNotFound();
            }

            return View(todoItem);
        }

       
        // POST: TodoItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var todoItem = await _context.TodoItems.SingleOrDefaultAsync(m => m.Id == id);
            _context.TodoItems.Remove(todoItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TodoItemExists(int id)
        {
            return _context.TodoItems.Any(e => e.Id == id);
        }
    }
}

TodoWebApp/Views/TodoItems/Create.cshtml
@model TodoWebApp.Models.TodoItem

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>TodoItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
@using (Html.BeginForm("Create", "TodoItems", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{                @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "ModelOnly", new { @class = "text-danger" })

            <div class="form-group">
                @Html.TextBoxFor(m => m.Value, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Value, "", new { @class = "text-danger" })
             
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
}
    </div>
</div>

<div>
   
    @Html.ActionLink("Back to List", "Index")
</div>

TodoWebApp/Views/TodoItems/Delete.cshtml
@model TodoWebApp.Models.TodoItem

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TodoItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>
    </dl>
    @using (Html.BeginForm("Delete", "TodoItems", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {                @Html.AntiForgeryToken()

        @Html.TextBoxFor(m => m.Id, new { type = "hidden", @class = "form-control" })

        <input type="submit" value="Delete" class="btn btn-default" /> 
    }
      <a asp-action="Index">Back to List</a>
    
</div>

TodoWebApp/Views/TodoItems/Details.cshtml
@model TodoWebApp.Models.TodoItem

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TodoItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Value)
            @Html.DisplayFor(model => model.Done)
        </dd>
    </dl>
</div>
<div>
    <a href="/TodoItems/Edit/@Model.Id">Edit</a> |
    @Html.ActionLink("Back to List", "Index")
</div>

TodoWebApp/Views/TodoItems/Edit.cshtml
@model TodoWebApp.Models.TodoItem

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>TodoItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
@using (Html.BeginForm("Edit", "TodoItems", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{                @Html.AntiForgeryToken()


            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                @Html.TextBoxFor(m => m.Value, new { @class = "form-control" })
                <br>
                @Html.LabelFor(m => m.Done) 
                @Html.CheckBoxFor(m => m.Done)

            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
     
}
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TodoWebApp/Views/TodoItems/Index.cshtml
@model IEnumerable<TodoWebApp.Models.TodoItem>

@{
    ViewData["Title"] = "Todo List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

                @Html.AntiForgeryToken()

<center>
    <h2>Todos</h2>
@using (Html.BeginForm("Create", "TodoItems", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{                @Html.AntiForgeryToken()

        <div class="form-group"> 
            <input id="Value" name="Value" class="form-control" value="Enter Here" />
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    }
</center>

<p>@Html.ActionLink("Completed", "Index", "TodoItems", new { area = "", filter="com" }, null)
    @Html.ActionLink("Active", "Index", "TodoItems", new { area = "", filter = "incom" }, null)
    @Html.ActionLink("All", "Index", "TodoItems", new { area = "", filter = "" }, null)
    @Html.ActionLink("Clear Completed", "DeleteCompleted", "TodoItems", new { area = "" }, null)
   
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Done)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WhenCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastAccessed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompleteDate)
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Value
                </td>
                <td>
                   @item.Done 
                </td>
                <td>
                    @item.WhenCreated
            </td>
            <td>
                @item.LastAccessed
            </td>
            <td>
                @item.CompleteDate
            </td>
                <td>
                    <a href="/TodoItems/Edit/@item.Id">Edit</a>
                    <a href="/TodoItems/Details/@item.Id">Details</a>
                    <a href="/TodoItems/Delete/@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>